### ISSUE TITLE
Unable to scan image using claircli

### ISSUE THREAD

**Issue by hakimkartik** [quay/clair#1017]
I wanted to scan my docker images using `Clair` , but I am getting the following error 
```
[achore :~] claircli -d -k "nexus-repo.xyzabc.com:8123:ZGVwbG95bWVudDpTcHIxbmtscjIwMTU" nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest
2020-07-16 10:47:22,441|INFO|*****************************1******************************
2020-07-16 10:47:22,441|INFO|Analyzing <Image: nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest>
2020-07-16 10:47:23,212|WARNING|'NoneType' object has no attribute 'group'
2020-07-16 10:47:23,212|DEBUG|Underlying problem:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/claircli/cli.py", line 181, in analyze_image
    clair.analyze_image(image)
  File "/usr/lib/python2.7/site-packages/claircli/clair.py", line 32, in analyze_image
    request('DELETE', '{}/{}'.format(self.api_v1_url, image.layers[0]))
  File "/usr/lib/python2.7/site-packages/claircli/docker_image.py", line 54, in layers
    manifest = self.manifest
  File "/usr/lib/python2.7/site-packages/claircli/docker_image.py", line 48, in manifest
    self._manifest = self.registry.get_manifest(self)
  File "/usr/lib/python2.7/site-packages/claircli/docker_registry.py", line 115, in get_manifest
    'Authorization': self.get_auth(image.repository)}
  File "/usr/lib/python2.7/site-packages/claircli/docker_registry.py", line 100, in get_auth
    params = {'service': matcher.group('service'),
AttributeError: 'NoneType' object has no attribute 'group'
2020-07-16 10:47:23,213|INFO|============================================================
2020-07-16 10:47:23,213|INFO|            CLAIR ANALYSIS REPORTS: (1) IN TOTAL
2020-07-16 10:47:23,213|INFO|============================================================
2020-07-16 10:47:23,213|ERROR|IMAGES WERE ANALYZED WITH ERROR (1)
2020-07-16 10:47:23,213|ERROR|nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest
[anchore~]
[anchore: /mnt1/karttik] claircli -d  nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest
2020-07-16 11:16:39,467|INFO|*****************************1******************************
2020-07-16 11:16:39,468|INFO|Analyzing <Image: nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest>
2020-07-16 11:16:40,215|WARNING|'NoneType' object has no attribute 'group'
2020-07-16 11:16:40,216|DEBUG|Underlying problem:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/claircli/cli.py", line 181, in analyze_image
    clair.analyze_image(image)
  File "/usr/lib/python2.7/site-packages/claircli/clair.py", line 32, in analyze_image
    request('DELETE', '{}/{}'.format(self.api_v1_url, image.layers[0]))
  File "/usr/lib/python2.7/site-packages/claircli/docker_image.py", line 54, in layers
    manifest = self.manifest
  File "/usr/lib/python2.7/site-packages/claircli/docker_image.py", line 48, in manifest
    self._manifest = self.registry.get_manifest(self)
  File "/usr/lib/python2.7/site-packages/claircli/docker_registry.py", line 115, in get_manifest
    'Authorization': self.get_auth(image.repository)}
  File "/usr/lib/python2.7/site-packages/claircli/docker_registry.py", line 100, in get_auth
    params = {'service': matcher.group('service'),
AttributeError: 'NoneType' object has no attribute 'group'
2020-07-16 11:16:40,216|INFO|============================================================
2020-07-16 11:16:40,216|INFO|            CLAIR ANALYSIS REPORTS: (1) IN TOTAL
2020-07-16 11:16:40,216|INFO|============================================================
2020-07-16 11:16:40,216|ERROR|IMAGES WERE ANALYZED WITH ERROR (1)
2020-07-16 11:16:40,216|ERROR|nexus-repo.xyzabc.com:8123/abc-centos7-base-image:latest
[anchore:~]

```
logs are as follows

```
[anchore :~] docker logs  --tail 80   mnt1_clair_1
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2020-07-16 09:01:42.001734"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2020-07-16 09:01:42.001781"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2020-07-16 09:01:42.001814","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2020-07-16 09:01:42.002077","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2020-07-16 09:01:42.002330","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2020-07-16 09:01:42.002579","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2020-07-16 09:01:42.002680","package":"RHEL"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 09:01:42.031188","updater name":"rhel"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 09:01:42.678501","updater name":"alpine"}
{"Event":"Debian bullseye is not mapped to any version number (eg. Jessie-\u003e8). Please update me.","Level":"warning","Location":"debian.go:134","Time":"2020-07-16 09:01:44.612460"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 09:01:44.612529","updater name":"debian"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 09:01:44.957516","updater name":"oracle"}
{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2020-07-16 09:01:49.265205","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 09:01:53.586967","updater name":"ubuntu"}
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:279","Time":"2020-07-16 09:01:53.811199"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:55.203059","data feed name":"2002","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:55.393302","data feed name":"2003","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:55.584112","data feed name":"2004","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:55.770736","data feed name":"2005","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:55.962086","data feed name":"2006","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:56.148709","data feed name":"2007","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:56.338381","data feed name":"2008","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:56.525067","data feed name":"2009","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:56.717946","data feed name":"2010","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:56.945829","data feed name":"2011","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:57.133714","data feed name":"2012","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:57.320287","data feed name":"2013","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:57.511941","data feed name":"2014","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:57.698991","data feed name":"2015","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:57.922488","data feed name":"2016","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:58.109700","data feed name":"2017","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:58.303910","data feed name":"2018","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:58.490505","data feed name":"2019","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 09:01:58.682671","data feed name":"2020","error":"invalid .meta file format"}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 09:06:05.040125","note":"Debian bullseye is not mapped to any version number (eg. Jessie-\u003e8). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 09:06:05.040166","note":"Ubuntu eoan is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 09:06:05.040188","note":"Ubuntu focal is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 09:06:05.040206","note":"Ubuntu disco is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 09:06:05.040226","note":"Ubuntu snap is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"update finished","Level":"info","Location":"updater.go:223","Time":"2020-07-16 09:06:05.041095"}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2020-07-16 11:06:05.001827"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2020-07-16 11:06:05.001885"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2020-07-16 11:06:05.001918","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2020-07-16 11:06:05.001990","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2020-07-16 11:06:05.002254","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2020-07-16 11:06:05.002536","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2020-07-16 11:06:05.002760","package":"Oracle Linux"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 11:06:05.091687","updater name":"rhel"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 11:06:05.647245","updater name":"alpine"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 11:06:06.476928","updater name":"oracle"}
{"Event":"Debian bullseye is not mapped to any version number (eg. Jessie-\u003e8). Please update me.","Level":"warning","Location":"debian.go:134","Time":"2020-07-16 11:06:07.684460"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 11:06:07.684540","updater name":"debian"}
{"Event":"could not parse package version. skipping","Level":"warning","Location":"ubuntu.go:316","Time":"2020-07-16 11:06:11.826019","error":"invalid version","version":"0.27-1+deb7u1build0.12.04.1, 0.28-1+deb8u1"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:253","Time":"2020-07-16 11:06:16.952801","updater name":"ubuntu"}
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:279","Time":"2020-07-16 11:06:17.202401"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:18.533878","data feed name":"2002","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:18.717504","data feed name":"2003","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:18.901183","data feed name":"2004","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:19.084720","data feed name":"2005","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:19.268192","data feed name":"2006","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:19.452186","data feed name":"2007","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:19.635819","data feed name":"2008","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:19.819392","data feed name":"2009","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.003146","data feed name":"2010","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.186504","data feed name":"2011","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.370015","data feed name":"2012","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.554129","data feed name":"2013","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.737471","data feed name":"2014","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:20.920853","data feed name":"2015","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:21.104195","data feed name":"2016","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:21.287911","data feed name":"2017","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:21.471302","data feed name":"2018","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:21.654671","data feed name":"2019","error":"invalid .meta file format"}
{"Event":"could not get NVD data feed hash","Level":"warning","Location":"nvd.go:137","Time":"2020-07-16 11:06:21.838090","data feed name":"2020","error":"invalid .meta file format"}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 11:10:30.132248","note":"Debian bullseye is not mapped to any version number (eg. Jessie-\u003e8). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 11:10:30.132300","note":"Ubuntu eoan is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 11:10:30.132323","note":"Ubuntu focal is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 11:10:30.132343","note":"Ubuntu disco is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"fetcher note","Level":"warning","Location":"updater.go:214","Time":"2020-07-16 11:10:30.132367","note":"Ubuntu snap is not mapped to any version number (eg. trusty-\u003e14.04). Please update me."}
{"Event":"update finished","Level":"info","Location":"updater.go:223","Time":"2020-07-16 11:10:30.133357"}
[anchore :~]
```
rest of the setup is as follows

```
[anchore :~] docker ps | grep clai
46ec872f594e        quay.io/coreos/clair:latest     "/clair -config=/con…"   25 hours ago        Up 25 hours             0.0.0.0:6060-6061->6060-6061/tcp   mnt1_clair_1
2e59425d4516        postgres:9.6                    "docker-entrypoint.s…"   25 hours ago        Up 25 hours             5432/tcp                           mnt1_clairdb_1
[anchore:/mnt1/karttik]
[anchore:/mnt1/karttik]
[anchore:/mnt1/karttik] docker images
REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
nexus-repo-int.xyzabc.com:8123/abc-centos7-base-image       latest              9cc38aea028d        9 days ago          336MB
nexus-repo.xyzabc.com:8123/abc-centos7-base-image           latest              9cc38aea028d        9 days ago          336MB
nexus-repo.xyzabc.com:8123/abc-centos7-base-image           test                9cc38aea028d        9 days ago          336MB
nexus-repo-int.xyzabc.com:8123/abc-centos7-base-image       test                9d61392b6196        9 days ago          336MB
postgres                                                      9                   51e37c2850c7        5 weeks ago         200MB
postgres                                                      9.6                 51e37c2850c7        5 weeks ago         200MB
nexus-repo-int.xyzabc.com:8123/abc-centos7-jdk11            latest              283702c433c0        5 weeks ago         914MB
anchore/anchore-engine                                        v0.7.2              a8257d7824a9        5 weeks ago         520MB
centos                                                        7                   b5b4d78bc90c        2 months ago        203MB
centos                                                        centos7             b5b4d78bc90c        2 months ago        203MB
nexus-repo-int.xyzabc.com:8123/cis-abc-centos7-base-image   latest              b5b4d78bc90c        2 months ago        203MB
nexus-repo-int.xyzabc.com:8123/abc-centos7-abhinav-test     latest              b5b4d78bc90c        2 months ago        203MB
nexus-repo.xyzabc.com:8123/cis-abc-centos7-base-image       latest              b5b4d78bc90c        2 months ago        203MB
nexus-repo-int.xyzabc.com:8123/abc-centos7-base-image       <none>              b5b4d78bc90c        2 months ago        203MB
quay.io/coreos/clair                                          latest              79f851f41934        16 months ago       355MB
[anchore :~] 
```

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
